name: CI + Deploy to Render

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main ]

concurrency:
  group: render-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Test (Jest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run tests
        env:
          NODE_ENV: test
        run: npm test

  deploy:
    name: Trigger Render Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/production'
    # Hacemos visibles secretos como env del job (para poder usarlos en if/env)
    env:
      RENDER_SERVICE_URL: ${{ secrets.RENDER_SERVICE_URL }}
    steps:
      - name: Trigger via Deploy Hook
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
            echo "❌ Falta el secreto RENDER_DEPLOY_HOOK"; exit 1
          fi
          echo "🚀 Disparando deploy en Render..."
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK"

      - name: Smoke test (optional)
        if: ${{ env.RENDER_SERVICE_URL != '' }}
        env:
          URL: ${{ env.RENDER_SERVICE_URL }}
        run: |
          echo "⏳ Esperando a que Render aplique el deploy..."
          sleep 40
          echo "🔎 GET $URL/health"
          curl -f "$URL/health"
          echo "✅ Deployment healthy"
